#!/bin/bash
#sh MAKEFILE
rm package-lock.json
git stash
git pull origin master
apt-get update

# reclaim ownership
sudo chown -R $USER ~/twilio_turn/
# set npm path
# npm config set prefix "node_modules"

npm install -g npm@latest
npm update
npm install
# audit Fix Auto and list modules
npm audit fix
npm list -g --depth 0
npm list
pm2 update

pm2 stop token.js
pm2 delete token.js

export TWILIO_ACCOUNT_SID=AC9bafc5120505da761c3a764aef4fcb00

pm2 start token.js

echo "$(hostname)"

echo "----server started------"
netstat -anp| grep 808
pm2 monit
